GET http://localhost:5123/books

###
GET http://localhost:5123/books/4

###
POST http://localhost:5123/books
Content-Type: application/json

{
    "name": "Book 4",
    "author": "Author 4",
    "publisher": "Publisher 4"
}

###
PUT http://localhost:5123/books/1
Content-Type: application/json

{
    "name": "Book 4",
    "author": "Author 4",
    "publisher": "Publisher 4"
}

###
DELETE http://localhost:5123/books/1
