GET http://localhost:5123/books

###
GET http://localhost:5123/books/10

###
POST http://localhost:5123/books
Content-Type: application/json

{
    "name": "Book 20 ",
    "publisher": "Publisher 2",
    "authorId": 1
}

###
PUT http://localhost:5123/books/2
Content-Type: application/json

{
    "name": "oke",
    "publisher": "Publisher 1",
    "authorId": 0
}

###
DELETE http://localhost:5123/books/1


//Author
###
GET http://localhost:5123/authors

###
GET http://localhost:5123/authors/10

###
POST http://localhost:5123/authors
Content-Type: application/json

{
    "name": "NSHOO",
    "dateOfBirth": "2000-01-01",
    "gender": "Male"
}

###
PUT http://localhost:5123/authors/1
Content-Type: application/json

{
    "name": "Author 1 ",
    "dateOfBirth": "2000-01-01",
    "gender": 0
}

###
DELETE http://localhost:5123/authors/1
